-- Mi Tienda Pro: data tables.
--
-- Every table mirrors a Dexie table (src/db/schema.ts): a primary-key column plus `data`, the whole
-- row exactly as its type in src/types defines it. The server only ever reads and writes whole
-- objects; the triggers below keep the rest consistent:
--   * sync_row      copies the primary key into `data` (so an inserted row comes back carrying its
--                   own generated id, like Dexie's `add`) and stamps `updated_at` with the real
--                   write time, the cursor of the clients' incremental sync;
--   * log_deletion  records every delete in `deletions`, so a device that was offline when a row
--                   was deleted still removes it on its next sync.
-- Identity ids are never reused, the same "stable ids" guarantee the old SQLite AUTOINCREMENT gave.
-- This file is plain Postgres (no Supabase roles or schemas) so `npm run check:cash` can load it
-- into an in-memory PGlite.

create function public.sync_row() returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.data := new.data || jsonb_build_object(tg_argv[0], to_jsonb(new) -> tg_argv[0]);
  new.updated_at := clock_timestamp();
  return new;
end
$$;

create table public.deletions (
  id bigint generated always as identity primary key,
  table_name text not null,
  pk text not null,
  deleted_at timestamptz not null default clock_timestamp()
);
create index deletions_deleted_at on public.deletions (deleted_at);

create function public.log_deletion() returns trigger
language plpgsql
set search_path = ''
as $$
begin
  insert into public.deletions (table_name, pk) values (tg_table_name, to_jsonb(old) ->> tg_argv[0]);
  return old;
end
$$;

-- Tables keyed by a natural or client-generated key.
create table public.products (code text primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());
create table public.customers (id text primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());
create table public.settings (key text primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());
create table public.usuarios (id text primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());
create table public.suppliers (id text primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());

-- Tables keyed by a server-generated id.
create table public.sales (id bigint generated by default as identity primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());
create table public.cierres (id bigint generated by default as identity primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());
create table public."auditLog" (id bigint generated by default as identity primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());
create table public.entradas (id bigint generated by default as identity primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());
create table public."cashMovements" (id bigint generated by default as identity primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());
create table public."cashSessions" (id bigint generated by default as identity primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());
create table public."purchaseOrders" (id bigint generated by default as identity primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());
create table public.payables (id bigint generated by default as identity primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());

create trigger sync_row before insert or update on public.products for each row execute function public.sync_row('code');
create trigger sync_row before insert or update on public.customers for each row execute function public.sync_row('id');
create trigger sync_row before insert or update on public.settings for each row execute function public.sync_row('key');
create trigger sync_row before insert or update on public.usuarios for each row execute function public.sync_row('id');
create trigger sync_row before insert or update on public.suppliers for each row execute function public.sync_row('id');
create trigger sync_row before insert or update on public.sales for each row execute function public.sync_row('id');
create trigger sync_row before insert or update on public.cierres for each row execute function public.sync_row('id');
create trigger sync_row before insert or update on public."auditLog" for each row execute function public.sync_row('id');
create trigger sync_row before insert or update on public.entradas for each row execute function public.sync_row('id');
create trigger sync_row before insert or update on public."cashMovements" for each row execute function public.sync_row('id');
create trigger sync_row before insert or update on public."cashSessions" for each row execute function public.sync_row('id');
create trigger sync_row before insert or update on public."purchaseOrders" for each row execute function public.sync_row('id');
create trigger sync_row before insert or update on public.payables for each row execute function public.sync_row('id');

create trigger log_deletion after delete on public.products for each row execute function public.log_deletion('code');
create trigger log_deletion after delete on public.customers for each row execute function public.log_deletion('id');
create trigger log_deletion after delete on public.settings for each row execute function public.log_deletion('key');
create trigger log_deletion after delete on public.usuarios for each row execute function public.log_deletion('id');
create trigger log_deletion after delete on public.suppliers for each row execute function public.log_deletion('id');
create trigger log_deletion after delete on public.sales for each row execute function public.log_deletion('id');
create trigger log_deletion after delete on public.cierres for each row execute function public.log_deletion('id');
create trigger log_deletion after delete on public."auditLog" for each row execute function public.log_deletion('id');
create trigger log_deletion after delete on public.entradas for each row execute function public.log_deletion('id');
create trigger log_deletion after delete on public."cashMovements" for each row execute function public.log_deletion('id');
create trigger log_deletion after delete on public."cashSessions" for each row execute function public.log_deletion('id');
create trigger log_deletion after delete on public."purchaseOrders" for each row execute function public.log_deletion('id');
create trigger log_deletion after delete on public.payables for each row execute function public.log_deletion('id');

-- Incremental sync reads "everything written after my cursor", per table.
create index products_updated_at on public.products (updated_at);
create index customers_updated_at on public.customers (updated_at);
create index settings_updated_at on public.settings (updated_at);
create index usuarios_updated_at on public.usuarios (updated_at);
create index suppliers_updated_at on public.suppliers (updated_at);
create index sales_updated_at on public.sales (updated_at);
create index cierres_updated_at on public.cierres (updated_at);
create index audit_log_updated_at on public."auditLog" (updated_at);
create index entradas_updated_at on public.entradas (updated_at);
create index cash_movements_updated_at on public."cashMovements" (updated_at);
create index cash_sessions_updated_at on public."cashSessions" (updated_at);
create index purchase_orders_updated_at on public."purchaseOrders" (updated_at);
create index payables_updated_at on public.payables (updated_at);

-- Lookups the server makes inside `data`.
create index customers_cedula on public.customers ((data ->> 'cedula'));
create index cash_movements_caja on public."cashMovements" ((data ->> 'caja'));
create index cash_sessions_status on public."cashSessions" ((data ->> 'status'));
create index purchase_orders_supplier on public."purchaseOrders" ((data ->> 'supplierId'));

-- Bumped whenever the data is reloaded wholesale (the import from the old SQLite server, a
-- restore): a device whose stored epoch differs drops its local mirror and pulls everything again.
create table public.sync_meta (key text primary key, value text not null);
insert into public.sync_meta (key, value) values ('epoch', '1');

-- The single settings row, with the same defaults as getSettings() in
-- src/db/repositories/settings.ts (PIN 1234). Replaced by the real settings when data is imported.
insert into public.settings (key, data)
values ('main', '{"key":"main","storeName":"Mi Tienda","pinHash":"03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4","pinLength":4,"theme":"light","hidScannerEnabled":true}');
