-- Mi Tienda Pro: Rutas — pedidos taken on a delivery round, prepared back at the shop, then
-- delivered and charged (which creates a normal `sales` row — see server/domain/routeOrders.ts,
-- `deliverRouteOrder` only links `saleId`, it never touches money itself). Same `data jsonb` +
-- trigger pattern as every other table (20261002000000_tables.sql); `sync_row`/`log_deletion`
-- already exist from that migration.

create table public."routeOrders" (id bigint generated by default as identity primary key, data jsonb not null, updated_at timestamptz not null default clock_timestamp());

create trigger sync_row before insert or update on public."routeOrders" for each row execute function public.sync_row('id');
create trigger log_deletion after delete on public."routeOrders" for each row execute function public.log_deletion('id');

create index route_orders_updated_at on public."routeOrders" (updated_at);
create index route_orders_status on public."routeOrders" ((data ->> 'status'));

alter table public."routeOrders" enable row level security;
create policy "staff can read" on public."routeOrders" for select to authenticated using ((select public.is_staff()));
revoke all on table public."routeOrders" from anon;
revoke insert, update, delete, truncate on table public."routeOrders" from authenticated;

alter publication supabase_realtime add table public."routeOrders";
